---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emojify-web-configmap
data:
  config: |
    window.env = {};
    window.env.config = {
      API_URL: '{{ .Values.api }}'
    };

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: emojify-website
  labels:
    app: emojify-website
spec:
  replicas: {{.Values.website_replicas}}
  selector:
    matchLabels:
      app: emojify-website
  template:
    metadata:
      labels:
        app: emojify-website
    spec:
      volumes:
        - name: config
          configMap:
            name: emojify-web-configmap
            items:
              - key: config
                path: env.js
      containers:
        - name: emojify-website
          image: "nicholasjackson/emojify-website:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config
              mountPath: /app/build/config/
              readOnly: true

        - name: emojify-website-proxy
          image: nicholasjackson/consul_connect_agent:latest
          command: ['/usr/local/bin/consul', 'connect', 'proxy']
          args: [
            "-log-level=DEBUG",
            "-service", "emojify-website",
            "-http-addr", "$(HOST_IP):8500",
            "-register",
            "-listen", "$(POD_IP):8443",
            "-service-addr", "localhost:5000"
          ]
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
